<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HL4FU21" failures="2" tests="2" name="Generate Order" time="25.804" errors="0" timestamp="2023-09-20T07:28:17 IST">
  <testcase classname="Junebatch2023.placeorder" name="Submitorder" time="22.748">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Junebatch2023.placeorder.Submitorder(placeorder.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Submitorder -->
  <testcase classname="Junebatch2023.placeorder" name="Submitorder" time="25.783">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)&amp;quot; because the return value of &amp;quot;java.lang.ThreadLocal.get()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because the return value of "java.lang.ThreadLocal.get()" is null
at testcomponents.Listeners.onTestFailure(Listeners.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- Submitorder -->
</testsuite> <!-- Generate Order -->
